import re

from codebase_kb.observability.logging import get_logger

log = get_logger(__name__)

def _slug(name: str) -> str:
    """Generates a URL-safe string for frontend routing."""
    s = re.sub(r"[^A-Za-z0-9_]+", "-", name).strip("-").lower()
    return s or "chapter"

def _build_overview_diagram(abstractions: list[dict], relationships: list[dict]) -> str:
    try:
        from codebase_kb.output.mermaid import build_overview_diagram, MermaidGenError
        return build_overview_diagram(abstractions, relationships)
    except (MermaidGenError, Exception) as e:
        log.warning("combine_tutorial.overview_diagram.skipped, error=%s", e)
        return ""
    
async def combine_tutorial_node(state: dict) -> dict:
    log.info("combine_tutorial.start, run_id=%s", state.get("run_id"))

    raw_chapters = state.get("chapters") or []
    abstractions = state.get("abstractions") or []
    relationships = state.get("relationships") or []
    chapter_order = state.get("chapter_order") or []

    if not raw_chapters or not chapter_order:
        log.warning("combine_tutorial.empty")
        return {"database_payload": None}
    
    project_name = state.get("project_name") or "tutorial"

    chapters_by_idx = {c["index"]: c for c in raw_chapters}
    ordered_chapters = []
    for abs_idx in chapter_order:
        if abs_idx in chapters_by_idx:
            ordered_chapters.append(chapters_by_idx[abs_idx])
    
    db_chapters = []
    toc_lines = []

    for i, chap in enumerate(ordered_chapters):
        chrono_num = i + 1
        current_md = chap["markdown"]
        abs_data = abstractions[chap["index"]]

        current_slug = f"{chrono_num:02d}-{_slug(abs_data['name'])}"
        # Resolve "Next: TBD" for Frontend SPA (e.g., /tutorial/02-authentication)
        if i < len(ordered_chapters) - 1:
            next_chap = ordered_chapters[i + 1]
            next_abs = abstractions[next_chap["index"]]
            next_slug = f"{chrono_num + 1:02d}-{_slug(next_abs['name'])}"
            
            # Using a relative hash/slug link that frontend routers (React/Next) can intercept
            link = f"\nNext: [{next_abs['name']}](#{next_slug})\n"
            current_md = re.sub(r"\n+Next: TBD\s*\n?$", link, current_md)
        else:
            current_md = re.sub(r"\n+Next: TBD\s*\n?$", "\n\n*You have completed the tutorial!*\n", current_md)
        
        # Build TOC Line using the same frontend-friendly anchor
        toc_lines.append(f"{chrono_num}. [{abs_data['name']}](#{current_slug}) — {abs_data.get('description', '')}")

        # Append to our structured database array
        db_chapters.append({
            "order": chrono_num,
            "title": abs_data["name"],
            "slug": current_slug,
            "markdown": current_md,
            "original_index": chap["index"]
        })

    # 4. Build the Index/Landing Page
    diagram = _build_overview_diagram(abstractions, relationships)
    summary = (state.get("summary") or "").strip()
    title = project_name.replace("_", " ").title()
    toc = "\n".join(toc_lines)

    index_md = [
        f"# {title}\n",
        f"_Generated by RepoAnalysis. Run ID: `{state.get('run_id', 'n/a')}`_\n",
        "## Architecture overview\n",
        "```mermaid" if diagram else "",
        diagram,
        "```\n" if diagram else "\n",
        "## Summary\n",
        summary or "_No summary available._\n",
        "## Table of contents\n",
        toc,
        "\n"
    ]
    
    # 5. The Final JSON Payload
    database_payload = {
        "project_name": project_name,
        "run_id": state.get("run_id"),
        "summary": summary,
        "index_markdown": "\n".join(index_md),
        "chapters": db_chapters,
        "total_chapters": len(db_chapters)
    }

    log.info("combine_tutorial.done, total_chapters=%s", len(db_chapters))
    
    # Return the structured payload directly to LangGraph state
    return {"database_payload": database_payload}